### ISSUE TITLE
Sidebar rows and switch stretch with size of icon

### ISSUE THREAD

**Issue by cassidyjames** [sapoturge/froggum#13]
I'm not entirely sure what this is supposed to look like or how to use it, but this looks pretty broken as-is.

![Screenshot from 2020-09-01 11-10-56](https://user-images.githubusercontent.com/611168/91890152-435c1800-ec4c-11ea-9af6-5ea869f09e40.png)

**Comment by sapoturge** [comment]
That is (almost) exactly what it's supposed to look like after creating a 128x128 icon. (The "almost" is because those buttons with the red stripes should have shades of gray in them, to match the fill and stroke colors of the default path.) The bar on the side is similar to the Layers panel on GIMP, including a view of the path. I could scale down that view of the paths on the side so it doesn't stretch out everything else. All of the buttons have tooltips, but that doesn't help with the editing viewport. You need to double-click on the path to select it, and editing can be done from there. I agree that the interface is unintuitive to begin; what could I do to make interaction more obvious?

**Comment by cassidyjames** [comment]
Was this fixed by #15? If so, could you submit a new release to AppCenter for review?

**Comment by sapoturge** [comment]
I'm still working on a few more updates. In particular, a basic tutorial so new users can get started. I'll should submit a new version soon.
